export const productData = [
  {
    id: "1",
    name: "Morden fabulous men sports shoose",
    price: 1748,
    video: "https://www.youtube.com/embed/864B4rzoPog",
    category: "men",
    brand: "puma",
    discount: 15,
  },
  {
    id: "2",
    name: "Morden fabulous men sports shoose",
    price: 1748,
    video: "https://www.youtube.com/embed/864B4rzoPog",
    category: "men",
    brand: "puma",
    discount: 10,
  },
  {
    id: "3",
    name: "Morden fabulous men sports shoose",
    price: 1748,
    video: "https://www.youtube.com/embed/864B4rzoPog",
    category: "men",
    brand: "puma",
    discount: 5,
  },
  {
    id: "4",
    name: "Morden fabulous men sports shoose",
    price: 1748,
    video: "https://www.youtube.com/embed/864B4rzoPog",
    category: "women",
    brand: "nike",
    discount: 10,
  },
  {
    id: "5",
    name: "Morden fabulous men sports shoose",
    price: 1748,
    video: "https://www.youtube.com/embed/864B4rzoPog",
    category: "women",
    brand: "puma",
    discount: 15,
  },
  {
    id: "6",
    name: "Morden fabulous men sports shoose",
    price: 1748,
    video: "https://www.youtube.com/embed/864B4rzoPog",
    category: "men",
    brand: "campus",
    discount: 15,
  },
  {
    id: "7",
    name: "Morden fabulous men sports shoose",
    price: 1748,
    video: "https://www.youtube.com/embed/864B4rzoPog",
    category: "kid",
    brand: "nike",
    discount: 15,
  },
  {
    id: "8",
    name: "Morden fabulous men sports shoose",
    price: 1748,
    video: "https://www.youtube.com/embed/864B4rzoPog",
    category: "kid",
    brand: "campus",
    discount: 15,
  },
];

export const category = ["men", "women", "kid"];
export const brand = ["puma", "nike", "campus"];
